
version: "3.9"

services:

  mariadb:
    image: mariadb
    pull_policy: never
    build:
      context: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
    volumes:
      - mariadb-data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception

  wordpress:
    image: wordpress
    pull_policy: never
    build:
      context: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD_FILE: ${WP_ADMIN_PASSWORD_FILE}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_REDIS_HOST: redis
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
      - redis
    secrets:
      - db_password
      - credentials
      - second_password
    networks:
      - inception

  nginx:
    image: nginx
    pull_policy: never
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception



  redis:
    image: redis
    pull_policy: never
    build:
      context: requirements/bonus/redis
    container_name: redis
    restart: always
    # Pas besoin de port 6379 exposé en dehors, réseau interne suffit
    networks:
      - inception

  ftp:
    image: ftp
    pull_policy: never
    build:
      context: requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    environment:
      FTP_USER: ${FTP_USER}
      # le fichier fourni automatiquement par Docker secrets :
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
    volumes:
      - wordpress-data:/var/www/html   # même volume que wordpress
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - wordpress
    secrets:
      - ftp_password          # 🔥 tu ajoutes ça
    networks:
      - inception


  adminer:
    image: adminer
    pull_policy: never
    build:
      context: requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"     # Adminer dispo sur http://localhost:8080
    networks:
      - inception

  mail:
    image: mail
    pull_policy: never
    build:
      context: requirements/bonus/mail
    container_name: mail
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # interface web
    networks:
      - inception


  static:
    build: requirements/bonus/static
    container_name: static
    ports:
      - "3000:80"
    networks:
      - inception



volumes:
  mariadb-data:
    driver_opts:
      type: none
      device: /home/throbert/data/mariadb
      o: bind

  wordpress-data:
    driver_opts:
      type: none
      device: /home/throbert/data/wordpress
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  second_password:
    file: ../secrets/second_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt


networks:
  inception:
    driver: bridge

