services:

  wordpress-fpm:
    build:
      context: .         # Dockerfile.wp se trouve dans le dossier courant
      dockerfile: Dockerfile.wp
    container_name: wordpress-fpm
    volumes:
      - ./wp-content:/var/www/html/wp-content
    expose:
      - 9000

  nginx:
    build:
      context: ./nginx   # Dockerfile.nginx dans le dossier nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - wordpress-fpm
    volumes:
      - ./wp-content:/usr/share/nginx/html
      - ./nginx/certs:/etc/ssl/certs
