bind 0.0.0.0
port 6379

# Désactiver le protected mode (ok car pas exposé à Internet)
protected-mode no

# Désactiver la persistance, on veut un cache pur RAM
save ""
appendonly no

# Dossier data obligatoire même si on ne persiste rien
dir /data

# Laisser Redis au premier plan pour Docker
daemonize no

# Optionnel : limites de mémoire (à adapter)
# maxmemory 256mb
# maxmemory-policy allkeys-lru
